import Head from 'next/head'
import Banner from '../components/Banner'
import Nav from '../components/Nav'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Vixens Esport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1.jpg" />
        <link href="https://fonts.cdnfonts.com/css/akira-expanded" rel="stylesheet" />
        <link href="https://fonts.cdnfonts.com/css/batmanforeveralternate" rel="stylesheet" />
      </Head>
      <Nav />
      <Banner />
    </div>
  )
}
